server:
    port: 8081
spring:
  application:
      name: zkt-biology
  cache:
      type: redis
  redis:
      database: 7
      host: ${REDIS_HOST:106.14.95.202}
      port: ${REDIS_PORT:9582}
      timeout: 1s
      password:
      jedis:
          pool:
              max-active: 20
              max-idle: 20
              max-wait: 1s
              min-idle: 10
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      url: jdbc:mysql://db.ibf.cn:3306/ag_admin_v1?useUnicode=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF8
      username: beifeng
      password: beifeng
      #url: jdbc:mysql://mysql.ibeifeng.cn:3306/ag_admin_v1?useUnicode=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF8
      #username: ace
      #password: Ibf@2018
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT1FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
      logSlowSql: true

mybatis:
  basepackage: com.zkt.project.biology.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"
logging:
  level:
     com.zkt.project.biology.mapper : debug

#配置接口相关
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY
  name: restapiuser
  expiresSecond: 172800